### ISSUE TITLE
Week12 is ready for grading

### ISSUE THREAD

**Issue by nmlund-matc** [madisoncollege-it-programs/python-scripting-nmlund-matc#16]

**Comment by cethenmc** [comment]
I like how you captured the full chat at the end.  A nice touch!  You have a minor issue though on the final transfer.  The server dies after your transfer.  As a result, I will give you a 7.5 out of 8.  If you want to resubmit, you can, but you are best served by getting moving on the Final Project.  I will close this ticket, thinking it is not worth your time.  However, if you finish the Final Project and want to finish this afterward, just email me letting me know the correction is done.  If I do not hear from you via email, then I assume you won't want to do this one.
