### ISSUE TITLE
Week3 strings.py is ready for grading!

### ISSUE THREAD

**Issue by nmlund-matc** [madisoncollege-it-programs/python-scripting-nmlund-matc#3]
No issues doing this script once you showed that varLoot:<.1f will round a number!

**Comment by cethenmc** [comment]
Hi, Nick.  Next time it may help to download the Word document assignment.  Technically, you should have had spaces between every "][" in #12 and 13.  Additionally, you should have had the same number of spaces in #13 as there were dollar signs in #12.  Please be more careful in week 4.  I will deduct it in the future.  ~Chris
