### ISSUE TITLE
Midterm-if.py is ready for grading!

### ISSUE THREAD

**Issue by nmlund-matc** [madisoncollege-it-programs/python-scripting-nmlund-matc#8]

**Comment by cethenmc** [comment]
All concepts you used were concepts learned in class, which was nice to see.  However, you have a few misses.  (1) Not using elifs:  What if you had a single line with both IP addresses in the same single line?  You would have duplicated the line number in the calculation. (2)  I assume you could not recall a method to extract the line number as requested.  As a result of not extracting the line number and converting it to an int once extracted, you ended up keeping a counter that mimicked the line numbers.  What if the file had gaps in the line number, or the line number stood for something else?  27/33
